sudo: false
cache: ccache
addons:
  apt:
    packages:
      - libxml2-dev
      - libreadline-dev
      - valgrind
install:
  - ./autogen.sh
  - sed -i '41s/ENOENT/ENOENT || errno == EINVAL/' gnulib/tests/test-readlink.h
language: c
notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#augeas"
script: ./configure && make -j 2 && make check -j 2 && ./src/try valgrind
